package org.wass.views.component;

import org.wass.controllers.product.StockController;
import org.wass.controllers.sale.FacturaController;
import org.wass.models.FacturaListModel;
import org.wass.models.TableDataModel;
import org.wass.models.sale.FacturaDao;
import org.wass.views.component.renderer.MapComboboxModel;
import org.wass.views.listeners.SearchListener;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * @author AlexBollen
 */
public class ViewVentas extends AbstractView implements Control {

    private VwHeader header;
    private MapComboboxModel<String, Integer> filterMap;

    private FacturaController controller;


    /**
     * Creates new form ViewVentas
     */
    public ViewVentas() {
        initComponents();
        componentesAdd();
    }

    private void componentesAdd() {
        filterMap = new MapComboboxModel<>();
        viewPanel = new JPanel();
        FacturaDao facturaDao = new FacturaDao();
        controller = new FacturaController(facturaDao);
        controller.setExceptionListener((excptn) -> {
            JOptionPane.showConfirmDialog(this, excptn.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        });

        header = new VwHeader();
        header.hideButtons();
        header.setTitle("Gestión - Ventas");
        jTableList.getTableHeader().setReorderingAllowed(false);
        jTableList.addMouseListener(new MouseAdapter() {
            @Override
            @SuppressWarnings("unchecked")
            public void mouseClicked(MouseEvent e){
            TableDataModel<FacturaListModel> model = (TableDataModel<FacturaListModel>) jTableList.getModel();
            }
        });
        setView(viewPanel);
        setHeader(header);

        addViewComponent(VC_LISTAR, jPanelListSales);
        showTable();

        showViewComponent(VC_LISTAR);
    }

    private void showTable() {
        TableModel model = controller.getSalesTable();
        for (int i = 0; i < model.getColumnCount(); i++) {
            filterMap.put(model.getColumnName(i), i);
        }

        jTableList.setModel(model);
        header.setMapComboboxModel(filterMap);
        header.getSearch().setTable(jTableList);
        header.getSearch().setSearchListener(new SearchListener() {
            @Override
            public int[] search() {
                return new int[] {
                  filterMap.getSelected()
                };
            }
            @Override
            public int limit() {
                return header.getLimitSlected();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelListSales = new javax.swing.JPanel();
        jPanelListSales.setLayout(new java.awt.BorderLayout());
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableList = new javax.swing.JTable();

        jTableList.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTableList);
        jPanelListSales.add(jScrollPane1, BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getComponenteTitle() { return "Gestión - Ventas"; }

    private JPanel viewPanel;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelListSales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableList;
    // End of variables declaration//GEN-END:variables
}
