package org.wass.views;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import org.wass.controllers.product.ProductoController;
import org.wass.controllers.purchase.CompraController;
import org.wass.controllers.purchase.EstadoCompraController;
import org.wass.controllers.purchase.ProveedorController;
import org.wass.controllers.purchase.TipoPagoController;
import org.wass.models.product.ProductoModel;
import org.wass.models.purchase.CompraModel;
import org.wass.models.purchase.DetalleCompraModel;
import org.wass.models.purchase.EstadoCompraModel;
import org.wass.models.purchase.ProveedorModel;
import org.wass.models.purchase.TipoPagoModel;
import org.wass.views.component.Control;

/**
 *
 * @author SamuelQ
 */
public class VistaCompras extends JPanel implements Control {

    private ProductoController productoController;
    private ProveedorController proveedorController;
    private TipoPagoController tipoPagoController;
    private EstadoCompraController estadoCompraController;
    private CompraController compraController;
    
    private TableRowSorter<DefaultTableModel> sorter;
    private DefaultTableModel productosTableModel;
    private DefaultTableModel comprasTableModel;

    /**
     * Creates new form DiseñoCompras
     */
    public VistaCompras() {
        this.productoController     = new ProductoController();
        this.proveedorController    = new ProveedorController();
        this.tipoPagoController     = new TipoPagoController();
        this.estadoCompraController = new EstadoCompraController();
        this.compraController       = new CompraController();

        initComponents();

        productosTableModel = new DefaultTableModel(new String[]{"ID", "Nombre", "Cantidad", "Precio Unitario", "Total"}, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        //Agregar Modelo para tabla de compras
        comprasTableModel = new DefaultTableModel(new String[]{"ID Compra", "Descripción", "Fecha Realizada", "Cantidad Pedida", "Cantidad Recibida", "Total", "Proveedor", "Tipo Pago", "Estado Compra"}, 0) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };

        //setear modelo a tabla
        tablaCompras.setModel(comprasTableModel);
        tablaCompras.getTableHeader().setReorderingAllowed(false);
        
        tablaProductos.setModel(productosTableModel);
        tablaProductos.getTableHeader().setReorderingAllowed(false);

        tablaCompras.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    accionesExtra.setVisible(true);
                    txtIdCompra.setText(String.valueOf(tablaCompras.getValueAt(tablaCompras.getSelectedRow(), 0)));
                    accionesExtra.revalidate();
                    accionesExtra.repaint();
                }
            }
        });
        
        
        //Crear el filtro
        
        sorter = new TableRowSorter<>(comprasTableModel);
        tablaCompras.setRowSorter(sorter);
        
        loadCompras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarCompra = new javax.swing.JButton();
        btnListarCompras = new javax.swing.JButton();
        cuerpo = new javax.swing.JPanel();
        listar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        comboBoxFiltroEstados = new JComboBox<>(new String[]{"Todos", "Pendiente", "Completada"});
        comboBoxFiltroEstados.addActionListener(e -> filtrarPorEstado((String) comboBoxFiltroEstados.getSelectedItem()));
        jLabel1 = new javax.swing.JLabel();
        agregar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelarCompra = new javax.swing.JButton();
        btnGuardarCompra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtareaDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        comboBoxProveedores = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboBoxProductos = new javax.swing.JComboBox<>();
        txtCantidadProducto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        comboBoxTipoPago = new javax.swing.JComboBox<>();
        txtCantidadPedida = new javax.swing.JTextField();
        txtTotalCompra = new javax.swing.JTextField();
        accionesExtra = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtIdCompra = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(794, 42));
        setLayout(new java.awt.BorderLayout());

        cabecera.setBackground(new java.awt.Color(0, 52, 89));
        cabecera.setForeground(new java.awt.Color(255, 255, 255));
        cabecera.setPreferredSize(new java.awt.Dimension(794, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administra y gestiona tus compras");

        btnAgregarCompra.setBackground(new java.awt.Color(0, 168, 232));
        btnAgregarCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarCompra.setForeground(new java.awt.Color(237, 242, 244));
        btnAgregarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Add.png")));
        btnAgregarCompra.setText("AGREGAR");
        btnAgregarCompra.setPreferredSize(new java.awt.Dimension(106, 31));
        btnAgregarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompraActionPerformed(evt);
            }
        });

        btnListarCompras.setBackground(new java.awt.Color(0, 168, 232));
        btnListarCompras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListarCompras.setForeground(new java.awt.Color(237, 242, 244));
        btnListarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/FileList.png")));
        btnListarCompras.setText("LISTAR");
        btnListarCompras.setPreferredSize(new java.awt.Dimension(106, 31));
        btnListarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarComprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 606, Short.MAX_VALUE)
                .addComponent(btnAgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnListarCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        add(cabecera, java.awt.BorderLayout.PAGE_START);

        cuerpo.setBackground(new java.awt.Color(237, 242, 244));
        cuerpo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cuerpo.setPreferredSize(new java.awt.Dimension(794, 42));
        cuerpo.setLayout(new java.awt.CardLayout());

        listar.setBackground(new java.awt.Color(237, 242, 244));
        listar.setPreferredSize(new java.awt.Dimension(794, 42));
        listar.setLayout(new java.awt.BorderLayout());

        jScrollPane6.setBackground(new java.awt.Color(255, 209, 102));

        tablaCompras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tablaCompras);

        jLabel1.setText("Filtrar por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(comboBoxFiltroEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxFiltroEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listar.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        cuerpo.add(listar, "card2");

        agregar.setBackground(new java.awt.Color(255, 209, 102));
        agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregar.setPreferredSize(new java.awt.Dimension(794, 42));
        agregar.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 52, 89));

        btnCancelarCompra.setBackground(new java.awt.Color(0, 168, 232));
        btnCancelarCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarCompra.setForeground(new java.awt.Color(237, 242, 244));
        btnCancelarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/FileDead.png")));
        btnCancelarCompra.setText("CANCELAR");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        btnGuardarCompra.setBackground(new java.awt.Color(0, 168, 232));
        btnGuardarCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarCompra.setForeground(new java.awt.Color(237, 242, 244));
        btnGuardarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Save.png")));
        btnGuardarCompra.setText("GUARDAR");
        btnGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(969, Short.MAX_VALUE)
                .addComponent(btnCancelarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarCompra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnGuardarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        agregar.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(237, 242, 244));

        jPanel4.setBackground(new java.awt.Color(237, 242, 244));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cantidad Pedida:");

        txtareaDescripcion.setColumns(20);
        txtareaDescripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtareaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtareaDescripcion);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total Compra:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Proveedor:");

        comboBoxProveedores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(237, 242, 244));

        btnAgregarProducto.setBackground(new java.awt.Color(141, 153, 174));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnEliminarProducto.setBackground(new java.awt.Color(141, 153, 174));
        btnEliminarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarProducto.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Producto:");

        comboBoxProductos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cantidad:");

        tablaProductos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(comboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarProducto))
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnEliminarProducto)
                    .addComponent(comboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tipo Pago:");

        comboBoxTipoPago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtCantidadPedida.setEditable(false);
        txtCantidadPedida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtTotalCompra.setEditable(false);
        txtTotalCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboBoxProveedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxTipoPago, 0, 142, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadPedida, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadPedida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTotalCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(87, 87, 87))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        agregar.add(jPanel3, java.awt.BorderLayout.CENTER);

        cuerpo.add(agregar, "card4");

        add(cuerpo, java.awt.BorderLayout.CENTER);

        accionesExtra.setBackground(new java.awt.Color(0, 52, 89));
        accionesExtra.setPreferredSize(new java.awt.Dimension(794, 42));

        jButton8.setBackground(new java.awt.Color(0, 168, 232));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(237, 242, 244));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/FileDead.png")));
        jButton8.setText("ELIMINAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel9.setText("Id Compra:");

        txtIdCompra.setEditable(false);

        javax.swing.GroupLayout accionesExtraLayout = new javax.swing.GroupLayout(accionesExtra);
        accionesExtra.setLayout(accionesExtraLayout);
        accionesExtraLayout.setHorizontalGroup(
            accionesExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accionesExtraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 882, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        accionesExtraLayout.setVerticalGroup(
            accionesExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesExtraLayout.createSequentialGroup()
                .addGroup(accionesExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jLabel9)
                    .addComponent(txtIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(accionesExtra, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getComponenteTitle() {
        return "COMPRAS";
    }

    private void btnAgregarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompraActionPerformed
        CardLayout l = (CardLayout) cuerpo.getLayout();
        l.show(cuerpo, "card4");
        limpiarDatos();
        loadProductos();
        loadProveedores();
        loadTipoPago();
    }//GEN-LAST:event_btnAgregarCompraActionPerformed

    private void btnListarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarComprasActionPerformed
        CardLayout l = (CardLayout) cuerpo.getLayout();
        l.show(cuerpo, "card2");
        loadCompras();
    }//GEN-LAST:event_btnListarComprasActionPerformed

    private void txtCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        agregarProducto();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        eliminarProducto();
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCompraActionPerformed
        finalizarCompra();
    }//GEN-LAST:event_btnGuardarCompraActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        // TODO add your handling code here:
        CardLayout l = (CardLayout) cuerpo.getLayout();
        l.show(cuerpo, "card2");
        loadCompras();
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            int idCompra = Integer.parseInt(txtIdCompra.getText());
            compraController.eliminarCompra(idCompra);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Seleccione una compra...");
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    
    //Método para filtrar por Estado de venta
    private void filtrarPorEstado(String estado){
        if(estado.equals("Todos")){
            sorter.setRowFilter(null);
        }else{
            sorter.setRowFilter(RowFilter.regexFilter(estado, 8));
        }
    }
    
    private void loadProductos() {
        comboBoxProductos.removeAllItems();
        try {
            List<ProductoModel> productos = productoController.obtenerProductos();
            for (ProductoModel producto : productos) {
                comboBoxProductos.addItem(producto); // Agrega los productos al ComboBox
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar productos: " + e.getMessage());
        }
    }

    private void loadProveedores() {
        comboBoxProveedores.removeAllItems();
        try {
            List<ProveedorModel> proveedores = proveedorController.obtenerProveedores();
            for (ProveedorModel proveedor : proveedores) {
                comboBoxProveedores.addItem(proveedor); // Agrega los proveedores al ComboBox
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar proveedores: " + e.getMessage());
        }
    }

    private void loadTipoPago() {
        comboBoxTipoPago.removeAllItems();
        try {
            List<TipoPagoModel> tipoPagoList = tipoPagoController.obtenerTiposPago();
            for (TipoPagoModel tipoPago : tipoPagoList) {
                comboBoxTipoPago.addItem(tipoPago); // Agrega los tipos de pago al ComboBox
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar tipos de pago: " + e.getMessage());
        }
    }

    private void agregarProducto() {
        ProductoModel productoSeleccionado = (ProductoModel) comboBoxProductos.getSelectedItem();
        
        int cantidad = Integer.parseInt(txtCantidadProducto.getText());
        float precioUnitario = productoSeleccionado.getPrecioVenta();

        float total = cantidad * precioUnitario;
        productosTableModel.addRow(new Object[]{productoSeleccionado.getIdProducto(), productoSeleccionado.getNombreProducto(), cantidad, precioUnitario, total});
        txtTotalCompra.setText(String.valueOf(obtenerTotalDeCompra()));
        txtCantidadPedida.setText(String.valueOf(obtenerCantidadSolicitada()));
        txtCantidadProducto.setText("");
    }

    private void eliminarProducto() {
        int selectedRow = tablaProductos.getSelectedRow();
        if (selectedRow >= 0) {
            productosTableModel.removeRow(selectedRow);
            txtTotalCompra.setText(String.valueOf(obtenerTotalDeCompra()));
            txtCantidadPedida.setText(String.valueOf(obtenerCantidadSolicitada()));
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un producto para eliminar.");
        }
    }

    @SuppressWarnings("deprecation")
    private void finalizarCompra() {
        ProveedorModel proveedorSeleccionado = (ProveedorModel) comboBoxProveedores.getSelectedItem();
        int idProveedor = proveedorSeleccionado.getIdProveedor();

        TipoPagoModel tipopagoSeleccionado = (TipoPagoModel) comboBoxTipoPago.getSelectedItem();
        int idTipoPago = tipopagoSeleccionado.getIdTipoPago();

        CompraModel compra;

        try {
            compra = new CompraModel("", 0, (float) 0, 0, 0);
            compra.setDescripcionCompra(txtareaDescripcion.getText());
            compra.setCantidadPedida(obtenerCantidadSolicitada());
            compra.setTotalCompra(obtenerTotalDeCompra());
            compra.setIdProveedor(idProveedor);
            compra.setIdTipoPago(idTipoPago);

            boolean resultado = compraController.agregarCompra(compra, obtenerListaDetalle());

            if (resultado) {
                JOptionPane.showMessageDialog(this, "Compra guardada exitosamente.");
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar la compra.");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private List<DetalleCompraModel> obtenerListaDetalle() {
        List<DetalleCompraModel> listaDetalles = new ArrayList<>();

        // Iterar sobre las filas de la tabla
        for (int row = 0; row < tablaProductos.getRowCount(); row++) {

            int idProducto = (int) tablaProductos.getValueAt(row, 0);
            int cantidad = (int) tablaProductos.getValueAt(row, 2); // Cantidad

            DetalleCompraModel detalle = new DetalleCompraModel(0, idProducto, cantidad);
            listaDetalles.add(detalle);
        }
        return listaDetalles;
    }

    private float obtenerTotalDeCompra() {
        float total = (float) 0;
        for (int row = 0; row < tablaProductos.getRowCount(); row++) {
            total += (float) tablaProductos.getValueAt(row, 4); // Total
        }
        return total;
    }

    private int obtenerCantidadSolicitada() {
        int cantidad = 0;
        for (int row = 0; row < tablaProductos.getRowCount(); row++) {
            cantidad += (int) tablaProductos.getValueAt(row, 2);
        }
        return cantidad;
    }

    private void limpiarDatos() {
        txtareaDescripcion.setText("");
        txtCantidadPedida.setText("");
        txtTotalCompra.setText("");
        txtCantidadProducto.setText("");
        productosTableModel.setRowCount(0);
        comprasTableModel.setRowCount(0);
        accionesExtra.setVisible(false);
    }

    private void loadCompras() {
        limpiarDatos();
        List<CompraModel> listaDeCompras = compraController.obtenerTodasLasCompras();

        for (CompraModel compra : listaDeCompras) {
            ProveedorModel proveedorBuscado = proveedorController.obtenerProveedorPorId(compra.getIdProveedor());
            String nombreProveedor = proveedorBuscado.getNombreComercial();

            TipoPagoModel tipopagoBuscado = tipoPagoController.obtenerTipoPagoPorId(compra.getIdTipoPago());
            String nombreTipoPago = tipopagoBuscado.getNombreTipoPago();

            EstadoCompraModel estadocompraBuscado = estadoCompraController.obtenerUnEstadoCompraPorId(compra.getIdEstadoCompra());
            String estadoCompra = estadocompraBuscado.getNombreEstadoCompra();

            // Insertar los datos en la tabla
            comprasTableModel.addRow(new Object[]{
                compra.getIdCompra(),
                compra.getDescripcionCompra(),
                compra.getFechaCompra(),
                compra.getCantidadPedida(),
                compra.getCantidadRecibida(),
                compra.getTotalCompra(),
                nombreProveedor,
                nombreTipoPago,
                estadoCompra
            });
        }

        // Asignar el modelo a la tabla
        tablaCompras.setModel(comprasTableModel);
    }
// <editor-fold defaultstate="collapsed" desc="Variables declaration"> 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accionesExtra;
    private javax.swing.JPanel agregar;
    private javax.swing.JButton btnAgregarCompra;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnGuardarCompra;
    private javax.swing.JButton btnListarCompras;
    private javax.swing.JPanel cabecera;
    private javax.swing.JComboBox<String> comboBoxFiltroEstados;
    private javax.swing.JComboBox<ProductoModel> comboBoxProductos;
    private javax.swing.JComboBox<ProveedorModel> comboBoxProveedores;
    private javax.swing.JComboBox<TipoPagoModel> comboBoxTipoPago;
    private javax.swing.JPanel cuerpo;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel listar;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCantidadPedida;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtIdCompra;
    private javax.swing.JTextField txtTotalCompra;
    private javax.swing.JTextArea txtareaDescripcion;
    // End of variables declaration//GEN-END:variables
// </editor-fold> 
}
