
package org.wass.views.purchase;


import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.wass.controllers.sale.ClienteController;
import org.wass.controllers.purchase.ProveedorController;
import org.wass.models.purchase.ProveedorModel;
import org.wass.views.component.Control;

/**
 *
 * @author marco
 */
public class ViewProveedores extends javax.swing.JPanel implements Control {

    private ClienteController clienteController;
    private ProveedorController proveedorController;
    private DefaultTableModel proveedorTableModel;
    private boolean actualizarB;
    private boolean agregarB;
    private int indiceId;
    private String nombre;
    private String direccion;
    private String telefono;
    private String nombreComercial;
    private String telefono2;
    private String correo;
    
    /**
     * Creates new form ViewClientes2
     */
    public ViewProveedores(ProveedorController proveedorController) {
        this.proveedorController = proveedorController;


        initComponents();
        
        
         //Agregar Modelo para tabla detalle de proveedores
            
        proveedorTableModel = new DefaultTableModel(new String[]{"ID","NombreComercial", "Telefono2", "Correo", "Nombre", "Telefono", "Direccion",  "Id Persona"}, 0) {
            boolean[] canEdit = new boolean[]{false, false, false, false, false, false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        
        tablaProveedores.setModel(proveedorTableModel);
        tablaProveedores.addMouseListener(new MouseAdapter() {
            
            public void mousePressed(MouseEvent e) {
                JTable table = (JTable) e.getSource();
                Point point = e.getPoint();
                int row = table.rowAtPoint(point);
                if (e.getClickCount() == 1){
                    accionesExtra.setVisible(true); 
                    txtIdProveedor.setText(String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 0)));
                    indiceId = Integer.parseInt(String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 0))) ;
                    accionesExtra.revalidate();
                    accionesExtra.repaint();
                }
                super.mousePressed(e);
            }
        });
        
        jTituloHeader.setText("Gestión de proveedores");
        loadProveedores();
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jTituloHeader = new javax.swing.JLabel();
        btnAgregarProveedor = new javax.swing.JButton();
        btnListarProveedor = new javax.swing.JButton();
        body = new javax.swing.JPanel();
        listar = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaProveedores = new javax.swing.JTable();
        agregar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelarCompra = new javax.swing.JButton();
        btnGuardarCompra = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombreComercial = new javax.swing.JTextField();
        accionesExtra = new javax.swing.JPanel();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtIdProveedor = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 595));
        setLayout(new java.awt.BorderLayout());

        header.setBackground(new java.awt.Color(0, 52, 89));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(100, 43));
        header.setMinimumSize(new java.awt.Dimension(100, 43));
        header.setPreferredSize(new java.awt.Dimension(100, 43));

        jTituloHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTituloHeader.setForeground(new java.awt.Color(255, 255, 255));
        jTituloHeader.setText("Gestión de Proveedores");

        btnAgregarProveedor.setBackground(new java.awt.Color(0, 168, 232));
        btnAgregarProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarProveedor.setForeground(new java.awt.Color(237, 242, 244));
        btnAgregarProveedor.setText("AGREGAR");
        btnAgregarProveedor.setPreferredSize(new java.awt.Dimension(106, 31));
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        btnListarProveedor.setBackground(new java.awt.Color(0, 168, 232));
        btnListarProveedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListarProveedor.setForeground(new java.awt.Color(237, 242, 244));
        btnListarProveedor.setText("LISTAR");
        btnListarProveedor.setPreferredSize(new java.awt.Dimension(106, 31));
        btnListarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTituloHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnListarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnListarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTituloHeader))
                .addContainerGap())
        );

        add(header, java.awt.BorderLayout.PAGE_START);

        body.setBackground(new java.awt.Color(237, 242, 244));
        body.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        body.setMaximumSize(new java.awt.Dimension(0, 0));
        body.setMinimumSize(new java.awt.Dimension(0, 0));
        body.setLayout(new java.awt.CardLayout());

        listar.setBackground(new java.awt.Color(237, 242, 244));
        listar.setMaximumSize(new java.awt.Dimension(0, 0));
        listar.setPreferredSize(new java.awt.Dimension(0, 0));
        listar.setLayout(new java.awt.BorderLayout());

        jScrollPane6.setBackground(new java.awt.Color(255, 209, 102));
        jScrollPane6.setMaximumSize(new java.awt.Dimension(1000, 1000));

        tablaProveedores.setBackground(new java.awt.Color(255, 255, 255));
        tablaProveedores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProveedores.setFillsViewportHeight(true);
        tablaProveedores.setShowGrid(true);
        jScrollPane6.setViewportView(tablaProveedores);

        listar.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        body.add(listar, "listar");

        agregar.setBackground(new java.awt.Color(255, 255, 255));
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 52, 89));

        btnCancelarCompra.setBackground(new java.awt.Color(0, 168, 232));
        btnCancelarCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarCompra.setForeground(new java.awt.Color(237, 242, 244));
        btnCancelarCompra.setText("CANCELAR");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });

        btnGuardarCompra.setBackground(new java.awt.Color(0, 168, 232));
        btnGuardarCompra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarCompra.setForeground(new java.awt.Color(237, 242, 244));
        btnGuardarCompra.setText("GUARDAR");
        btnGuardarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(537, Short.MAX_VALUE)
                .addComponent(btnCancelarCompra)
                .addGap(30, 30, 30)
                .addComponent(btnGuardarCompra)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnGuardarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        agregar.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(237, 242, 244));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Dirección");

        txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Telefono");

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Correo");

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtTelefono2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Telefono");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("NombreComercial");

        txtNombreComercial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(338, 338, 338))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(71, 71, 71)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(57, 57, 57)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(49, 49, 49)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(78, 78, 78))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono)
                            .addComponent(jLabel11))
                        .addGap(254, 254, 254))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreComercial)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono2)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo)
                            .addComponent(jLabel14))
                        .addGap(254, 254, 254))))
        );

        agregar.add(jPanel3, java.awt.BorderLayout.CENTER);

        body.add(agregar, "agregar");

        add(body, java.awt.BorderLayout.CENTER);

        accionesExtra.setBackground(new java.awt.Color(0, 52, 89));
        accionesExtra.setEnabled(false);

        jButtonActualizar.setBackground(new java.awt.Color(0, 168, 232));
        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(237, 242, 244));
        jButtonActualizar.setText("ACTUALIZAR");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonEliminar.setBackground(new java.awt.Color(0, 168, 232));
        jButtonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(237, 242, 244));
        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Id Proveedor:");

        javax.swing.GroupLayout accionesExtraLayout = new javax.swing.GroupLayout(accionesExtra);
        accionesExtra.setLayout(accionesExtraLayout);
        accionesExtraLayout.setHorizontalGroup(
            accionesExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accionesExtraLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel9)
                .addGap(27, 27, 27)
                .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        accionesExtraLayout.setVerticalGroup(
            accionesExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accionesExtraLayout.createSequentialGroup()
                .addGroup(accionesExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonActualizar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jLabel9)
                    .addComponent(txtIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(accionesExtra, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String getComponenteTitle() {
        return "Proveedores";
    }
    
    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        jTituloHeader.setText("Agregar nuevo proveedor");
        CardLayout l = (CardLayout) body.getLayout();
        l.show(body, "agregar");
        limpiarDatos();
        agregarB = true;
        actualizarB = false;
        
        
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void btnListarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProveedorActionPerformed
        jTituloHeader.setText("Gestión de proveedores");
       CardLayout l = (CardLayout) body.getLayout();
        l.show(body, "listar");
        loadProveedores();
    }//GEN-LAST:event_btnListarProveedorActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        llenarTextBox();
        jTituloHeader.setText("Actualizar proveedor con id: "+ indiceId);
        limpiarDatos();
        CardLayout l = (CardLayout) body.getLayout();
        l.show(body, "agregar");
        agregarB = false;
        actualizarB = true;
        
        System.out.println(telefono);
        txtNombre.setText(nombre);
        txtDireccion.setText(direccion);
        txtTelefono.setText(telefono);
        txtNombreComercial.setText(nombreComercial);
        txtCorreo.setText(correo);
        txtTelefono2.setText(telefono2);
        
       
        
        
        
      
     
        
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
         int opcion = JOptionPane.showConfirmDialog(null,
            "¿Está seguro de eliminar al proveedor: "+String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 1))+"?",
             "Eliminar proveedor",
            JOptionPane.OK_CANCEL_OPTION);
       if (opcion == JOptionPane.OK_OPTION){
           eliminarProveedor();
       }
      
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        // TODO add your handling code here:
        CardLayout l = (CardLayout) body.getLayout();
        l.show(body, "listar");
        loadProveedores();
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void btnGuardarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCompraActionPerformed
        if(agregarB){
            guardarProveedor();
        }
        
        else if(actualizarB){
            actualizarProveedor();
        }
        
        actualizarB = false;
        agregarB = false;
        
    }//GEN-LAST:event_btnGuardarCompraActionPerformed
 
    
    
    private void limpiarDatos(){
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtNombreComercial.setText("");
        txtTelefono2.setText("");
        txtCorreo.setText("");
        proveedorTableModel.setRowCount(0);
        accionesExtra.setVisible(false);
    }
    
    private void llenarTextBox(){
        nombreComercial = String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 1));
        telefono2 = String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 2));
        correo = String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 3));
        nombre = String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 4));
         telefono = String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 5));
        direccion = String.valueOf(tablaProveedores.getValueAt(tablaProveedores.getSelectedRow(), 6));
       
        
        
    }
    
     private void eliminarProveedor() {
         
        int selectedRow = tablaProveedores.getSelectedRow();
        if (selectedRow >= 0) {
            proveedorTableModel.removeRow(selectedRow);
           boolean   resultado = proveedorController.eliminarProveedor(indiceId);
            if (resultado) {
                JOptionPane.showMessageDialog(this, "Proveedor exterminado exitosamente.");
                limpiarDatos();
                loadProveedores();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el proveedor.");
            }        
           
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona un cliente para eliminar.");
        }
    }
     
     private void guardarProveedor(){
         ProveedorModel proveedor = null;
         
         try{
             proveedor = new ProveedorModel("", "","",0,"","", "");
             proveedor.setNombrePersona(txtNombre.getText());
             proveedor.setDireccion(txtDireccion.getText());
             proveedor.setTelefono(txtTelefono.getText());
             proveedor.setNombreComercial(txtNombreComercial.getText());
             proveedor.setTelefono2(txtTelefono2.getText());
             proveedor.setCorreo(txtCorreo.getText());
             
             boolean resultado = proveedorController.agregarProveedorPersona(proveedor);
             
              if (resultado) {
                JOptionPane.showMessageDialog(this, "Proveedor guardado exitosamente.");
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar el proveedor.");
            }        
             
         }
         catch (Exception e){
             JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
         }
         
         
         jTituloHeader.setText("Gestión de proveedores");
         CardLayout l = (CardLayout) body.getLayout();
            l.show(body, "listar");
         loadProveedores();
     }
     
     private void actualizarProveedor(){
         ProveedorModel proveedor = null;
         try{
             proveedor = new ProveedorModel("", "","",0,"","", "");
             proveedor.setNombrePersona(txtNombre.getText());
             proveedor.setDireccion(txtDireccion.getText());
             proveedor.setTelefono(txtTelefono.getText());
             proveedor.setNombreComercial(txtNombreComercial.getText());
             proveedor.setTelefono2(txtTelefono2.getText());
               proveedor.setCorreo(txtCorreo.getText());
             
             boolean resultado = proveedorController.actualizarProveedor(proveedor, indiceId);
             
              if (resultado) {
                JOptionPane.showMessageDialog(this, "Proveedor actualizado exitosamente.");
                limpiarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el proveedor.");
            }        
             
         }
         catch (Exception e){
             JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
         }
         
         jTituloHeader.setText("Gestión de proveedores ");
         CardLayout l = (CardLayout) body.getLayout();
         l.show(body, "listar");
         loadProveedores();
     }
    
 private void loadProveedores(){
        limpiarDatos();
        List<ProveedorModel> listaProveedores = proveedorController.obtenerProveedores();

        for (ProveedorModel proveedor : listaProveedores) {
        
        // Insertar los datos en la tabla
        proveedorTableModel.addRow(new Object[]{
            proveedor.getIdProveedor(),
            proveedor.getNombreComercial(),
            proveedor.getTelefono2(),
            proveedor.getCorreo(),
            proveedor.getNombrePersona(),
            proveedor.getTelefono(),
            proveedor.getDireccion(),
            proveedor.getIdPersona()
        });
        
        
    // Asignar el modelo a la tabla
    
    tablaProveedores.setModel(proveedorTableModel);
    }
    
 }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accionesExtra;
    private javax.swing.JPanel agregar;
    private javax.swing.JPanel body;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnGuardarCompra;
    private javax.swing.JButton btnListarProveedor;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel jTituloHeader;
    private javax.swing.JPanel listar;
    private javax.swing.JTable tablaProveedores;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdProveedor;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreComercial;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
